"""add new feature

Revision ID: fc0bfa77ff5a
Revises: 5d8b746712b6
Create Date: 2025-08-17 01:57:55.718360

"""

# revision identifiers, used by Alembic.
revision = "fc0bfa77ff5a"
down_revision = "5d8b746712b6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
