"""add priority field to prompts

Revision ID: 34065a4cc718
Revises: fc0bfa77ff5a
Create Date: 2025-08-17 08:24:55.246092

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "34065a4cc718"
down_revision = "fc0bfa77ff5a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prompts", sa.Column("priority", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prompts", "priority")
    # ### end Alembic commands ###
